export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const GET_MEAT_CATEGORY = 'GET_MEAT_CATEGORY'
export const GET_FRUIT_CATEGORY = 'GET_FRUIT_CATEGORY'
export const SET_LOADING = 'SET_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'
export const GET_VEGETABLES_CATEGORY = 'GET_MVEGETABLESCATEGORY'

// cart
export const ADD_TO_CART = 'ADD_TO_CART'